#ifndef TP0_ORGACOMPUTADORAS_CONSTANTS_H
#define TP0_ORGACOMPUTADORAS_CONSTANTS_H

extern const int MAX_RULE_NUMBER;
extern const char* HELP_MESSAGE;
extern const char* VERSION_MESSAGE;

#endif //TP0_ORGACOMPUTADORAS_CONSTANTS_H
